import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  materialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // 從 docs 根目錄自動生成
    },
  ],
};

export default sidebars;