import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  materialSidebar: [
    'summary',
    {
      type: 'category',
      label: '易用性',
      collapsed: true,
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'usability' }],
    },
    {
      type: 'category',
      label: '可維護性',
      collapsed: true,
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'maintainable' }],
    },
    {
      type: 'category',
      label: '高可用性',
      collapsed: true,
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'high-availability' }],
    },
    {
      type: 'category',
      label: '附錄',
      collapsed: true,
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'appendix' }],
    }
  ],
};

export default sidebars;
